Rabi frequencies
OxfordIonTrapGroup/atomic_physics pull request #73
Opened 2024-12-23 18:37 UTC by AVB25

Essentially, this is a completion of the TODO in Atom.calc_Epole about the connection between the stored scattering amplitudes and the experimentally measurable Rabi frequencies. Instead of documentation, it adds functions for directly calculating Rabi frequencies and other related quantities like light shift (AC Stark shift) frequencies. There are a couple of other things added, such as a broader ```Beam``` object to store a laser beam's parameters. This could replace the ```Laser``` object if desired.

2024-12-23 18:41 UTC, AVB25 commented
I think this mostly agrees with experiment, except the quadrupole Rabi frequencies it predicts have been around 2.3 times faster than those found in ABaQuS. I'm not sure whether the discrepancy is due to maths or experimental parameters not being fully known. 

One thing I maybe suspect is the conversion from Cartesian to Spherical coordinates. The conversion I've done is mostly from https://doi.org/10.1007/s003400050373 with some fudging of signs to make the Rank 1 tensor components agree with what is usually used, but the maths in Section 4.5 of Angular Momentum by Brink and Satchler gives slightly different results. However, it would make the discrepancy bigger.

2024-12-23 18:57 UTC, AVB25 commented
(Formatting)

2024-12-23 21:11 UTC, hartytp requested changes
Great to have some work towards handling scattering amplitudes properly etc.

However, a PR along these lines is unlikely to get merged because it doesn't respect and work with some of the basic design decisions behind this package. I'll go into some detail below and in the comments to illustrate what I mean.

In terms of going from here to something mergeable, I'd suggest you try to break this down into a series of smaller PRs which do just one thing (e.g. a small util function for calculating Rayleigh ranges if you feel that's useful) rather than a single large PR which really does a few unconnected things.


Examples of ways this PR doesn't work with the design behind this package:
* we deliberately chose not to have a `State` object because we want to work at arbitrary magnetic fields where `F` is not well-defined (although there _is_ a helper until already provided to aid with this)
* we chose to work in saturation intensity units, now power / waist
* we chose to deal with polarization based on the change in angular momentum for the transition it drives, not polarization angles
* we chose to specify laser frequencies in terms of a detuning from a transition, rather than an absolute wavelength

There is obviously no single convention which is best in every situation, but one has to adopt a representation and work with it, rather than having multiple things which do the same thing in different ways. If you want a different convention, the best approach would be to add a few util functions to help with the conversions - or, if you feel strongly that we should change the fundamental design, to open a discussion issue for one specific point.

Beyond that, the `Beam` object really feels like it groups a few things together which don't need to belong together - just helper functions.

Also, there are no tests! Before merging something like this I'd want to see some tests which exercise the new functionality - e.g. comparing calculations to known good values from literature / trusted theses.

2024-12-23 21:14 UTC, hartytp commented
> I think this mostly agrees with experiment, except the quadrupole Rabi frequencies it predicts have been around 2.3 times faster than those found in ABaQuS. I'm not sure whether the discrepancy is due to maths or experimental parameters not being fully known.

> One thing I maybe suspect is the conversion from Cartesian to Spherical coordinates. The conversion I've done is mostly from https://doi.org/10.1007/s003400050373 with some fudging of signs to make the Rank 1 tensor components agree with what is usually used, but the maths in Section 4.5 of Angular Momentum by Brink and Satchler gives slightly different results. However, it would make the discrepancy bigger.

Better to either (a) resolve this kind of discrepancy before opening this PR or (b) explicitly mark the PR as a draft. It's not really clear what the intent behind this PR is - are you looking for a review and merge, or just opening as a placeholder while you do some more thinking?

FWIW the sign conventions here are a bit messy. The big thing I was looking for in my todo was to get really clear (and document! e.g. adding a markdown document if needed) on what conventions we're using and avoid fudges.

2024-12-23 21:21 UTC, hartytp commented
NB there is some related discussion in:
* https://github.com/OxfordIonTrapGroup/atomic_physics/issues/27
* https://github.com/OxfordIonTrapGroup/atomic_physics/issues/29
* https://github.com/OxfordIonTrapGroup/atomic_physics/issues/19

Those issues outline the approach I would expect us to take here.

2024-12-26 14:39 UTC, AVB25 commented
Thank you for the detailed comments, I appreciate you adding all that info and links.

Having read them, I agree with you that the approach I took was not the correct one - and that I probably rushed to raise a PR on something that wasn't ready for that yet. The main intention behind the PR was that I had written this code for some simulation recent simulation work and spent a fair bit of time learning how to go from the scattering rates in ```ePole``` to a physical Rabi frequency. Other PhDs in the group then mentioned that they also had to go through a similar process, so I thought it would be useful to make this code available as part of the package since calculations of Rabi frequencies and other similar quantities feel like a natural extension of its current utility. However, in doing so, I more or less directly copied the functions I had used without thinking about how they'd fit in with the rest of the package, which I now realise was not the best thing to do - apologies. 

Regarding the TODO on the quadrupole transitions, I agree that this is not in a state that is mergeable - I will find comparisons with literature and include them in tests. 

I also agree that splitting this up into smaller PRs/issues would make this more manageable. Shall I close this PR, unless you have anything else to add?

2025-01-07 21:21 UTC, hartytp commented
@AVB25 thanks for the contribution.

I spent some time over the holiday refreshing the API for atomic physics as well as improving documentation and testing - largely inspired by this PR. I think it's now in a better place to tackle this.

If you're still interested in taking this forward, I suggest a good small issue to tackle first would be https://github.com/OxfordIonTrapGroup/atomic_physics/issues/86 Do you want to give that a go?

2025-01-07 21:21 UTC, closed without merging

2025-01-07 21:22 UTC, hartytp commented
Another self-contained PR would be to add a helper function to create an arbitrary elliptical polarization based on angles (see the `polarization` module and tests). If we do this, the main things I'm keen on are having good docs (either docstring or adding to the definitions / conventions page in the manual, being clear about things like definitions of angles and sign conventions / handedness. Maybe even include an ASCII art / SVG image illustrating how we define angles).

2025-01-08 09:49 UTC, AVB25 commented
Thank you for this! And yes! I'd be more than happy to take both forward.